name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger the workflow on tags starting with 'v'

jobs:
  build_and_release:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build Executable
        run: |
          pyinstaller --name mypass-service --onefile service.py

      - name: Move Executable to dist/
        run: |
          mkdir -p dist
          mv dist/mypass-service dist/mypass-service-$os

      # Add a check step to verify if the executables exist
      - name: Verify Executables
        run: ls dist

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          files: |
            dist/*
          tag_name: ${{ steps.tag_name.outputs.tag_name }}
          title: Release ${{ steps.tag_name.outputs.tag_name }}
          draft: false
          prerelease: ${{ steps.is_prerelease.outputs.is_prerelease == 'true' }}
